[workspace]
resolver = "2"
members = [
    "crates/ragelab-hash",
    "crates/ragelab-assets",
    "crates/ragelab-authoring",
    "crates/ragelab-engine",
    "crates/ragelab-render",
    "crates/ragelab-rpf",
    "crates/ragelab-resource",
    "crates/ragelab-rbf",
    "crates/ragelab-meta",
    "crates/ragelab-pso",
    "crates/ragelab-ymap",
    "crates/ragelab-ytd",
    "crates/ragelab-ytyp",
    "crates/ragelab-ymf",
    "crates/ragelab-ydr",
    "crates/ragelab-yft",
    "crates/ragelab-ydd",
    "crates/ragelab-ybn",
    "crates/ragelab-wasm",
    "apps/ragelab",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.80"

[workspace.lints.rust]
unsafe_code = "forbid"
